dbt_transformation:
  outputs:
    dev:
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET', '') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE_PATH', '') }}"
      location: "US"
      method: service-account
      priority: interactive
      project: "big-star-420419"
      threads: 1
      type: bigquery
  target: dev