dbt_transformation:
  outputs:
    dev:
      dataset: "{{ env_var('transformed_data', '') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('/Users/ahmed.soliman/workspace/ahmed/personal/data-eng/big-star-420419-61bab6eb8c72.json', '') }}"
      location: "{{ env_var('US', '') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('big-star-420419', '') }}"
      threads: 1
      type: bigquery
  target: dev